config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  get 'items/create'

  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :users, only: [:new, :create]

  resources :lists do 
    resources :items
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  validates_presence_of :description

  STATUS = {
    :incomplete => 0,
    :complete => 1
  }

  def complete?
    self.status == STATUS[:complete]
  end

  def incomplete?
    self.status == STATUS[:incomplete]
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email
  validates_presence_of :email

  has_secure_password

  def self.find_or_create_by_omniauth(auth_hash)
    self.where(email: auth_hash["info"]["email"]).first_or_create do |user|
      user.password = SecureRandom.hex
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authentication_required
    if !logged_in?
      redirect_to login_path
    end
  end 

  def logged_in?
    !!current_user
  end 

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  #METHODS YOU BUILD IN THE CONTROLLER DO NOT PERMEATE TO THE ACTIONVIEW PART OF YOUR CODE,
  #UNLESS YOU EXPLICITLY YOU CAN'T CALL THIS ON YOUR HTML.ERB

  #THIS IS A HELPER METHOD, PLEASE LET ME USE THIS IN MY VIEW:

  helper_method :current_user 

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(items_params)
    if @item.save
      redirect_to list_path(@list)
    else
      render '/lists/show'
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.update(items_params)

    redirect_to list_path(@item.list)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to list_path(@item.list)
  end



  private

  def items_params
    params.require(:item).permit(:description, :status)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authentication_required

  def index
    #if you are not logged in, you can't see this page, in fact, go back to the login page
    @list = List.new
    @lists = List.all
  end

  def create
    @list = List.new(list_params)

    if @list.valid?
      @list.save
      redirect_to list_path(@list)
    else
      @lists = List.all
      render :index
    end
  end


  def show 
    @list = List.find(params[:id])
    @item = Item.new
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create 
    if auth_hash = request.env["omniauth.auth"]
      user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = user.id

      redirect_to root_path

    else
      #normal Login with Username & Password
      user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id

        redirect_to root_path
      else
        render 'sessions/new'
      end
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    #User model validations for =>  if !@user.nil? && !User.exists?(user_params) 
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'users/new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def li_class_for_item(item)
    "completed" if item.complete?
  end

  def li_for_item(item)
    content_tag_for :li, item, class: li_class_for_item(item) do
      yield
    end
  end

  def form_for_item_status(item)
    form_for([item.list, item]) do |f| 
      f.check_box :status, :class => "toggle", :checked => item.complete? 
    end 
  end

  def form_for_item_delete(item)
    button_to "x", list_item_path(item.list, item), :method => "delete", :class => "destroy"
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item_li.html.erb
<%= li_for_item(item) do %>
  <div class="view">
    <%= form_for_item_status(item)%>

    <label><%= item.description %></label>

    <%= form_for_item_delete(item) %>
  </div>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoMvcLv</title>
  <%= stylesheet_link_tag    'application', media: 'all', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

  <footer class="footer">
    <p><%= link_to "Logout", logout_path %></p>
  </footer>

</body>
</html>



  

app/views/lists/index.html.erb
<section class="todoapp">
  <header class="header">
    <h1>TODO List</h1>
    <%= form_for(@list) do |f| %>
      <%= f.text_field :name, :class => "new-todo", :placeholder => (@list.errors.full_messages_for(:name).first || "Create a new List!") %>
      <%= f.submit :style => "display: none" %>
    <% end %>
  </header>
  <section class="main" style="display: block">
    <input class="toggle-all" type="checkbox">
    <label for="toggle-all">Mark all as complete</label>
    <ul class="todo-list">
      <% @lists.each do |list| %>
        <li>
          <div class="view">
            <label><%= link_to list.name, list_path(list) %></label>
          </div>  
        </li>
       <% end %> 
    </ul>
  </section>
  <footer class="footer">
    <p> You're logged in as: <%= current_user.email %></p>
  </footer>
</section>

app/views/lists/show.html.erb
<section class="todoapp">
  <header class="header">
    <h1><%= @list.name %></h1>
    <%= form_for([@list, @item]) do |f| %>
      <%= f.text_field :description, :class => "new-todo", :placeholder => (@item.errors.full_messages_for(:description).first || "Enter a new item...") %>
      <%= f.submit :style => "display: none" %>
    <% end %>
  </header>
  <section class="main">
    <input class="toggle-all" type="checkbox">
    <label for="toggle-all">Mark all as complete</label>
    <ul class="todo-list">
      <%= render :collection => @list.items, :partial => "items/item_li", as: :item %>
    </ul>
  </section>
  <footer class="footer">
  </footer>
</section>

app/views/users/new.html.erb
<section class="todoapp">
  <header class="header">
    <h1>Signup!</h1>
    <%= form_for(@user) do |f| %>
      <%= f.text_field :email, class: "new-todo", placeholder: "Register your e-mail here!" %>
      <%= f.text_field :password, class: "new-todo", placeholder: "Choose a password" %>
      <%= f.text_field :password_confirmation, class: "new-todo", placeholder: "Please confirm your password" %>
      <%= f.submit %>
    <% end %>  
  </header>
  <footer class="footer">

  </footer>
</section>